baseURL = 'https://hescaide.me/'
languageCode = 'en-us'
title = "Holy-Elie Scaide's Website"
theme = 'minima'
[params]
  brand = 'Hash'
  switch = ["ğŸŒš", "ğŸŒ"]
  defaultTheme = "system"
[menu]
[[menu.main]]
  identifier = 'about'
  name = "About"
  pageRef = 'about'
  weight = 20
[[menu.main]]
  identifier = 'portfolio'
  name = "What I've done"
  pageRef = '/portfolio'
  weight = 20
[[menu.main]]
  identifier = 'antilibrary'
  name = 'Antilibrary'
  pageRef = '/'
  weight = 30
